### ISSUE TITLE
host/port config location

### ISSUE THREAD

**Issue by hansmosh** [nioinnovation/project_template#2]
Why are host, port and instance_name under "communication" in config?
https://github.com/nioinnovation/project_template/blob/master/nio.conf#L37

**Comment by mattdodge** [comment]
@f1401martin, can you confirm that we don't need those 3 settings in the communication module anywhere? If so, we can remove them

**Comment by f1401martin** [comment]
Yes, can be removed

**Comment by mattdodge** [comment]
This has been fixed with the new configuration file changes
